### ISSUE TITLE
disabling shader effects

### ISSUE THREAD

**Issue by ghost** [Z-15/Halo-Infinite-Tag-Editor#1]
hi, would it be possible to allow nulling out shader effects like you can in infinite runtime tag viewer?
in your tag editor you can't do anything with them, you can click them and they highlight but nothing happens.

![shadereffects](https://user-images.githubusercontent.com/88882159/196135091-4cd68b1a-cf68-489b-8c03-0585140f5cf1.jpg)

edit, i guess it's just not supported right now as other things like values in tag reference properties like hud overlays can't be nulled out either.

**Comment by Z-15** [comment]
They are still being worked on. Editing them seems to be more complicated than at runtime because there are multiple sections that need editing. I'll probably work on clearing them first as I believe that would be the simplest thing to do.

**Comment by ghost** [comment]
ok, will look forward to when the feature is added. will continue to use the runtime tool for now.
appreciate the reply :)
